### ISSUE TITLE
How am I suppose to initialize Cloudcast?

### ISSUE THREAD

**Issue by tng10** [emillon/mixcloud#13]
Can you guys provide an example in docs? Thanks

**Comment by emillon** [comment]
Hi,

Sure, the actual arguments are missing in the README. Sorry about that!
I'll add something about that, but in the meantime if you want to have a look you can check out how `Cloudcast.from_yml` builds the object.

Thanks!

**Comment by efpresence** [comment]
i'd like to bump this request, please! :)

**Comment by emillon** [comment]
Hi! you can find an example in the tests:

https://github.com/emillon/mixcloud/blob/da4c7a70444c7f1712ee13e3a93eb1cd9c3f4ab8/tests.py#L37-L54

Please note that this project was done in a fairly ad-hoc way and I'm not maintaining it anymore, so I would not recommend depending on it too much.
